.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

glabel __osError
/* A6AD0 800A5ED0 3C08800F */  lui        $t0, %hi(jtbl_800EAA84)
/* A6AD4 800A5ED4 8D08AA84 */  lw         $t0, %lo(jtbl_800EAA84)($t0)
/* A6AD8 800A5ED8 11000003 */  beqz       $t0, .L800A5EE8
/* A6ADC 800A5EDC 00000000 */   nop
/* A6AE0 800A5EE0 01000008 */  jr         $t0
/* A6AE4 800A5EE4 00000000 */   nop
.L800A5EE8:
/* A6AE8 800A5EE8 03E00008 */  jr         $ra
/* A6AEC 800A5EEC 00000000 */   nop
.size __osError, . - __osError
