.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

/* Handwritten function */
glabel osGetCount
/* A87E0 800A7BE0 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
/* A87E4 800A7BE4 03E00008 */  jr         $ra
/* A87E8 800A7BE8 00000000 */   nop
/* A87EC 800A7BEC 00000000 */  nop
.size osGetCount, . - osGetCount

