.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

/* Handwritten function */
glabel __osGetSR
/* A79A0 800A6DA0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
/* A79A4 800A6DA4 03E00008 */  jr         $ra
/* A79A8 800A6DA8 00000000 */   nop
/* A79AC 800A6DAC 00000000 */  nop
.size __osGetSR, . - __osGetSR

