.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

/* Handwritten function */
glabel __osSetSR
/* A7990 800A6D90 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
/* A7994 800A6D94 00000000 */  nop
/* A7998 800A6D98 03E00008 */  jr         $ra
/* A799C 800A6D9C 00000000 */   nop
.size __osSetSR, . - __osSetSR
