name: decomp.dev Progress

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  progress:
    name: Upload progress report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload progress report
        uses: actions/upload-artifact@v4
        with:
          name: us1_report
          path: versions/us1/us1_report.json
