.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

glabel func_80099BC0
/* 9A7C0 80099BC0 00000000 */  nop
/* 9A7C4 80099BC4 00000000 */  nop
/* 9A7C8 80099BC8 00000000 */  nop
/* 9A7CC 80099BCC 00000000 */  nop
/* 9A7D0 80099BD0 00000000 */  nop
/* 9A7D4 80099BD4 00000000 */  nop
/* 9A7D8 80099BD8 00000000 */  nop
/* 9A7DC 80099BDC 00000000 */  nop
/* 9A7E0 80099BE0 00000000 */  nop
/* 9A7E4 80099BE4 00000000 */  nop
/* 9A7E8 80099BE8 00000000 */  nop
/* 9A7EC 80099BEC 00000000 */  nop
/* 9A7F0 80099BF0 00000000 */  nop
/* 9A7F4 80099BF4 00000000 */  nop
/* 9A7F8 80099BF8 00000000 */  nop
/* 9A7FC 80099BFC 00000000 */  nop
/* 9A800 80099C00 00000000 */  nop
/* 9A804 80099C04 00000000 */  nop
/* 9A808 80099C08 00000000 */  nop
/* 9A80C 80099C0C 00000000 */  nop
/* 9A810 80099C10 00000000 */  nop
/* 9A814 80099C14 00000000 */  nop
/* 9A818 80099C18 00000000 */  nop
/* 9A81C 80099C1C 00000000 */  nop
.size func_80099BC0, . - func_80099BC0

